const $=id=>document.getElementById(id),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ASPECTS=['1:1','2:3','3:4','3:5','4:5','5:7','5:8','7:9','9:16','9:19','9:21','9:32','3:2','4:3','5:3','5:4','7:5','8:5','9:7','16:9','19:9','21:9','2.39:1','32:9'];
$('aspect').innerHTML=ASPECTS.map(a=>`<option>${a}</option>`).join('');
function dimensions(aspect,longEdge=1024){const [w,h]=aspect.split(':').map(Number),scale=longEdge/Math.max(w,h);return [Math.max(32,Math.round(w*scale/32)*32),Math.max(32,Math.round(h*scale/32)*32)]}

function setTheme(theme){document.documentElement.dataset.theme=theme;$('themeToggle').textContent=theme==='dark'?'日间':'夜间';try{localStorage.setItem('frame-theme',theme)}catch{}}
let initialTheme='light';try{initialTheme=localStorage.getItem('frame-theme')||'light'}catch{}setTheme(initialTheme);$('themeToggle').onclick=()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');
let ready=false;
let P=null,segIndex=0,shotId='',token='',cfg={},saveTimer,dirty=false,saveChain=Promise.resolve();
const newId=()=>crypto.randomUUID().replaceAll('-','').slice(0,12),seg=()=>P?.segments[segIndex],shot=()=>seg()?.shots.find(s=>s.id===shotId);
function toast(t){$('toast').textContent=t;$('toast').style.display='block';clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').style.display='none',5000)}
async function api(path,body){const opts={headers:{'X-Workbench-Token':token}};if(body!==undefined){opts.method='POST';opts.body=body instanceof File?body:JSON.stringify(body);opts.headers['Content-Type']=body instanceof File?'application/zip':'application/json'}const r=await fetch('/api/'+path,opts);const data=await r.json();if(!r.ok||data?.error)throw Error(data.error||'请求失败');return data}
async function safe(fn){try{await fn()}catch(e){toast(e.message)}}
function changed(){dirty=true;$('saved').textContent='有未保存修改';clearTimeout(saveTimer);saveTimer=setTimeout(()=>safe(flush),600)}
function flush(){clearTimeout(saveTimer);if(!dirty||!P)return saveChain;dirty=false;const snapshot=JSON.parse(JSON.stringify(P));saveChain=saveChain.catch(()=>{}).then(()=>api('project',snapshot)).then(()=>{if(!dirty)$('saved').textContent='已保存在本机'}).catch(e=>{dirty=true;$('saved').textContent='保存失败';throw e});return saveChain}
function image(path){if(!path||!P?.media[path])return '';const ext=path.split('.').at(-1).toLowerCase();let mime=({webp:'image/webp',jpg:'image/jpeg',jpeg:'image/jpeg',jfif:'image/jpeg',gif:'image/gif',bmp:'image/bmp',avif:'image/avif',tif:'image/tiff',tiff:'image/tiff'})[ext]||'image/png';return 'data:'+mime+';base64,'+P.media[path]}
function imgTag(path){return image(path)?`<img src="${image(path)}" data-preview="${esc(path)}" alt="参考素材" title="点击放大查看" tabindex="0" role="button" draggable="false">`:''}
function ranges(){let previous=0;const notes=[];for(const s of seg()?.shots||[]){if(s.end<=s.start||s.start<0||s.end>seg().duration+.001)notes.push('存在超出片段或时长无效的镜头');if(Math.abs(s.start-previous)>.05)notes.push('时间线存在间隙或重叠');previous=s.end}if(seg()&&Math.abs(previous-seg().duration)>.05)notes.push('镜头尚未覆盖完整片段');return [...new Set(notes)]}
function render(){
 ensureAssetNumbers();if(P&&!P.assetsManaged){activateAssetManagement();changed()}
 $('projectTitle').value=P?.title||'未命名项目';$('script').value=workspaceText(P?.script||'',true);$('aspect').value=P?.aspect||'16:9';
 if(typeof renderSegmentList==='function')renderSegmentList();else $('segments').innerHTML=(P?.segments||[]).map((s,i)=>`<button class="segment ${i===segIndex?'active':''}" data-seg="${i}"><span class="num">${String(i+1).padStart(2,'0')}</span><span><b>${esc(s.title)}</b><small>${s.duration.toFixed(1)} SEC · ${s.shots.length} 镜头 ${s.continuity?'· 衔接':''}</small></span></button>`).join('');
 if(typeof syncDialogueLanguage==='function')syncDialogueLanguage();
 renderAssets();
 const s=seg();$('segmentTitle').textContent=s?.title||'开始你的分镜';$('undoShots').hidden=!seg()?.shotHistory?.length;$('clearShots').disabled=!seg()?.shots?.length;$('segmentMeta').textContent=s?`${s.duration.toFixed(1)} 秒 / ${P.aspect} / ${s.shots.length} 镜头${s.continuity?' / 文字承接上一段':''}${(s.guideFromPrev??s.continuity)&&segIndex>0?' / 视频段间引导':''}`:'导入导演包，或从一个故事开始';
 $('board').innerHTML=s?s.shots.map((sh,i)=>{const context=s.refs?.[0]?.imageFile;const pic=sh.image||context;return `<article class="shot ${sh.id===shotId?'selected':''}" draggable="true" data-shot="${sh.id}"><div class="shothead"><span>SHOT ${String(i+1).padStart(2,'0')}</span><span>${sh.start.toFixed(1)}–${sh.end.toFixed(1)}s</span></div><div class="shotvisual">${imgTag(pic)||'<span class="placeholder">＋</span>'}${!sh.image&&pic?'<span class="sceneBadge">片段参考图</span>':''}</div><div class="shotbody"><p>${typeof highlightMentions==='function'?highlightMentions(workspaceText(sh.action||'点击编辑镜头动作'),'group'):esc(workspaceText(sh.action||'点击编辑镜头动作'))}</p><div class="tags"><span>${sh.camera?'运镜已设置':'待设运镜'}</span><span class="duration">${(sh.end-sh.start).toFixed(1)}s</span></div></div></article>`}).join(''):'<div class="empty">分镜还没有开始。<br>添加片段和镜头开始策划。</div>';
 $('timeline').innerHTML=(s?.shots||[]).map((sh,i)=>`<button class="${sh.id===shotId?'selected':''}" data-shot="${sh.id}" style="flex:${Math.max(.1,sh.end-sh.start)}" title="${esc(workspaceText(sh.action))}">${String(i+1).padStart(2,'0')}<small>${(sh.end-sh.start).toFixed(1)}s</small></button>`).join('');$('timelineTotal').textContent=s?`${s.duration.toFixed(1)} SEC`:'';$('timelineEnd').textContent=s?`00:${s.duration.toFixed(1)}`:'';
 const warnings=ranges();$('warning').hidden=!warnings.length;$('warning').textContent=warnings.join('；')+'。';renderEditor();if(typeof syncStudioPanel==='function')syncStudioPanel();if(typeof syncReversePanel==='function')syncReversePanel();if(typeof refreshMentionEditors==='function')refreshMentionEditors();if(typeof syncWorkbenchState==='function')syncWorkbenchState();if(typeof syncSegmentVideos==='function')syncSegmentVideos();if(typeof syncSpatialEditor==='function')syncSpatialEditor();
}
function renderEditor(){const sh=shot();if(typeof renderProfessionalEditor==='function')renderProfessionalEditor(sh);$('editForm').hidden=!sh;$('emptyEditor').hidden=!!sh;$('shotNumber').textContent=sh?String(seg().shots.indexOf(sh)+1).padStart(2,'0'):'—';if(!sh)return;$('editorImage').innerHTML=imgTag(sh.image)||'<span>尚未生成分镜图</span>';$('frameThumbs').innerHTML=[['firstFrame','首帧'],['lastFrame','尾帧']].map(([key,label])=>sh[key]?`<div>${imgTag(sh[key])}<small>${label}</small></div>`:'').join('');for(const k of ['start','end','action','camera','expression','dialogue','sound'])$(k).value=['start','end'].includes(k)?sh[k]||'':workspaceText(sh[k]||'');$('locks').innerHTML=Object.entries({identity:'身份',costume:'服装',scene:'场景',prop:'道具'}).map(([k,l])=>`<button data-lock="${k}" class="${sh.locks?.[k]?'active':''}">${sh.locks?.[k]?'🔒 ':''}${l}</button>`).join('')}
let modalRevision=0;
function modal(title,html,buttons=[]){modalRevision++;for(const video of $('modalBody').querySelectorAll('video'))video.pause();$('modalBody').onclick=null;$('modalTitle').textContent=title;$('modalBody').innerHTML=html;$('modalActions').innerHTML='';for(const b of buttons){const el=document.createElement('button');el.textContent=b.label;el.className=b.class||'';el.onclick=()=>safe(async()=>{el.disabled=true;try{await b.action()}finally{el.disabled=false}});$('modalActions').append(el)}if(!$('modal').open){if(document.documentElement.dataset.referenceLibrary==='true')$('modal').show();else $('modal').showModal();}if(typeof refreshMentionEditors==='function')refreshMentionEditors()}
function close(){hideMentions();$('modal').close()}
function normalize(){let at=0;for(const sh of seg().shots){const duration=Math.max(.1,sh.end-sh.start);sh.start=Number(at.toFixed(3));at+=duration;sh.end=Number(at.toFixed(3))}}
async function updatePrompt(){const s=seg();if(s){s.prompt=(await api('rebuild',{...s,defaultDialogueLanguage:P.dialogueLanguage||'',assetReferences:availableAssets(s).map(a=>({index:assetNumber(a),name:a.name,kind:a.kind,description:a.description||''}))})).prompt;changed()}}
async function edited(){await updatePrompt();render()}
function ensure(){
 let created=false;
 if(!P){P={version:1,projectId:newId(),title:'新导演项目',script:'',aspect:'16:9',fps:24,segments:[],assets:[],media:{},originalZip:''};created=true}
 if(!seg()){P.segments.push({id:newId(),title:'片段 01',duration:15,originalDuration:15,prompt:'',originalPrompt:'',shots:[],refs:[],continuity:false});segIndex=P.segments.length-1;created=true}
 if(created)changed()
}
async function readImage(file,project=P){if(!file)return '';if(file.size>30*1024*1024)throw Error('单张素材上限 30MB');let data=await new Promise((res,rej)=>{const r=new FileReader;r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)});if(file.type==='image/jpeg')data=await uprightImageData(data,'image/jpeg');const ext=file.type==='image/jpeg'?'.jpg':file.type==='image/webp'?'.webp':'.png';if(P!==project)throw Error('项目已切换，图片未写入新项目');const path='storyboard_media/'+newId()+ext;project.media[path]=data.split(',')[1];return path}
$('closeModal').onclick=close;
$('segments').onclick=e=>{const b=e.target.closest('[data-seg]');if(b){segIndex=Number(b.dataset.seg);shotId=seg().shots[0]?.id||'';render()}};
function selectShot(e){const b=e.target.closest('[data-shot]');if(b){shotId=b.dataset.shot;render()}}
$('board').onclick=e=>{selectShot(e)};$('timeline').onclick=selectShot;
let dragId='';$('board').ondragstart=e=>{const card=e.target.closest('[data-shot]');if(card){dragId=card.dataset.shot;e.dataTransfer.setData('text/plain',dragId)}};$('board').ondragover=e=>e.preventDefault();$('board').ondrop=e=>safe(async()=>{e.preventDefault();const to=e.target.closest('[data-shot]')?.dataset.shot;if(!to||to===dragId)return;const shots=seg().shots;const a=shots.findIndex(s=>s.id===dragId),b=shots.findIndex(s=>s.id===to);if(a<0||b<0)return;shots.splice(b,0,shots.splice(a,1)[0]);normalize();await edited()});
for(const key of ['action','camera','expression','dialogue','sound'])$(key).onchange=()=>safe(async()=>{shot()[key]=storedWorkspaceText($(key).value);await edited()});
for(const key of ['start','end'])$(key).onchange=()=>safe(async()=>{const v=Number($(key).value);if(!Number.isFinite(v))return;shot()[key]=v;await edited()});
$('locks').onclick=e=>safe(async()=>{const k=e.target.closest('[data-lock]')?.dataset.lock;if(!k)return;shot().locks[k]=!shot().locks[k];changed();renderEditor()});
$('projectTitle').oninput=()=>{ensure();P.title=$('projectTitle').value;changed()};$('script').oninput=()=>{ensure();P.script=storedWorkspaceText($('script').value);changed()};$('aspect').onchange=()=>{ensure();P.aspect=$('aspect').value;changed();render()};
$('import').onclick=()=>$('packFile').click();$('packFile').onchange=()=>safe(async()=>{const f=$('packFile').files[0];if(!f)return;await flush();if(P&&!confirm('导入将替换当前本机项目。建议先导出备份，继续吗？'))return;P=await api('import',f);segIndex=0;shotId=seg()?.shots[0]?.id||'';dirty=false;render();toast('导演包已导入：'+P.segments.length+' 段'+(P.importWarnings?.length?'；'+P.importWarnings.length+' 张图片未在包内找到，请拖图替换：'+P.importWarnings.join('、'):''));$('packFile').value=''});
$('newProject').onclick=()=>safe(async()=>{if(!ready)throw Error('工作台正在加载，请稍候');$('newProject').disabled=true;try{await flush();P=await api('new-project',{});segIndex=0;shotId='';dirty=false;$('jobStatus').textContent='';$('instruction').value='';render();$('saved').textContent='新项目已保存在本机';toast('已新建空白项目；上一项目已自动备份')}finally{$('newProject').disabled=false}});
async function downloadDirectorPack(force=false){const r=await fetch(force?'/api/export-force':'/api/export',{method:force?'POST':'GET',headers:{'X-Workbench-Token':token,...(force?{'Content-Type':'application/json'}:{})},...(force?{body:JSON.stringify({projectId:P.projectId,acknowledgeConflicts:true})}:{})});if(!r.ok)throw Error((await r.json()).error);const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download=(P.title.replace(/[\\/:*?"<>|]/g,'_')||'Storyboard')+'.mmxpack.zip';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);toast(force?'已强制导出；未解决问题已附在包内。':'导演包已导出。请在 H3 导演台验证导入。')}
$('export').onclick=()=>safe(async()=>{
 if(!P)throw Error('先建立或导入项目');await flush();const pid=P.projectId;
 const report=await api('prompt-quality',{projectId:pid});const entries=report.segments.filter(s=>s.issues.length);const blocked=entries.some(s=>s.issues.some(i=>i.severity==='error'));
 if(!entries.length)return downloadDirectorPack();
 modal('导演包导出检查',`<p class="notice">${blocked?'发现需要修复的冲突，普通导出暂不导出。可定位修改、智能修复，或保留当前内容强制导出。':'以下项目需要人工核对，规则检查不能保证生成质量。确认后可继续导出。'}</p><p class="muted">智能修复使用已确认的素材说明与文字模型，不重新分析图片；完成后在任务中心预览并应用，再导出。强制导出不会修改内容，未解决问题随包附带。</p><p id="qualityActionStatus" class="notice" hidden></p>${entries.map(s=>`<article><b>${esc(s.title)}</b> <button data-quality-repair="${esc(s.id)}">智能修复本片段</button>${s.issues.map(i=>`<p class="${i.severity==='error'?'warning':'muted'}">${esc((i.severity==='error'?'需修复：':'需核对：')+i.message)} <button data-quality-segment="${esc(s.id)}" data-quality-shot="${i.shotIndex||''}">定位${i.shotIndex?'镜头 '+i.shotIndex:'片段'}</button></p>`).join('')}</article>`).join('')}`,[{label:'关闭',action:close},{label:'任务中心',action:openTaskCenter},{label:'强制导出',action:async()=>{if(P?.projectId!==pid)throw Error('项目已切换');if(!confirm('强制导出将保留当前提示词及未解决冲突，可能影响生成结果。问题清单会附进导演包。继续导出？'))return;await flush();await downloadDirectorPack(true);close()}},...(!blocked?[{label:'已核对，继续导出',class:'primary',action:async()=>{if(P?.projectId!==pid)throw Error('项目已切换');await flush();await downloadDirectorPack();close()}}]:[])]);
 $('modalBody').onclick=e=>safe(async()=>{
 const repair=e.target.closest('[data-quality-repair]');if(repair){if(P?.projectId!==pid)throw Error('项目已切换');repair.disabled=true;try{await flush();const row=await api('smart-repair',{projectId:pid,segmentId:repair.dataset.qualityRepair});$('qualityActionStatus').hidden=false;$('qualityActionStatus').textContent='智能修复已排队，请在任务中心查看进度；完成后预览并应用。';repair.textContent='已提交智能修复';return}catch(err){repair.disabled=false;$('qualityActionStatus').hidden=false;$('qualityActionStatus').textContent=err.message;return}}
 const b=e.target.closest('[data-quality-segment]');if(!b)return;if(P?.projectId!==pid)throw Error('项目已切换');await flush();segIndex=P.segments.findIndex(s=>s.id===b.dataset.qualitySegment);if(segIndex<0)throw Error('片段已删除');shotId=seg().shots[Number(b.dataset.qualityShot||1)-1]?.id||'';close();render();toast('请修改动作、起止状态及摘要；摘要可在片段设置中修改。')});
});
$('addSegment').onclick=()=>{if(!P){ensure();render();return}P.segments.push({id:newId(),title:'片段 '+String(P.segments.length+1).padStart(2,'0'),duration:15,originalDuration:15,prompt:'',originalPrompt:'',shots:[],refs:[],continuity:true});segIndex=P.segments.length-1;shotId='';changed();render()};
$('addShot').onclick=()=>safe(async()=>{ensure();const s=seg();const start=s.shots.at(-1)?.end||0;const end=start<s.duration?Math.min(start+3,s.duration):start+3;const sh={id:newId(),start,end,action:'',camera:'',expression:'',dialogue:'',sound:'',image:'',firstFrame:'',lastFrame:'',locks:{identity:true,costume:false,scene:true,prop:false}};s.shots.push(sh);shotId=sh.id;await edited()});
$('deleteShot').onclick=()=>safe(async()=>{if(!shot()||!confirm('删除这个镜头？'))return;seg().shots=seg().shots.filter(s=>s.id!==shotId);normalize();shotId=seg().shots[0]?.id||'';await edited()});
for(const [id,delta] of [['moveLeft',-1],['moveRight',1]])$(id).onclick=()=>safe(async()=>{const shots=seg().shots;const i=shots.findIndex(s=>s.id===shotId),j=i+delta;if(i<0||j<0||j>=shots.length)return;[shots[i],shots[j]]=[shots[j],shots[i]];normalize();await edited()});
$('editSegment').onclick=()=>{ensure();modal('片段设置',`<label>片段名称<input id="mTitle" value="${esc(seg().title)}"></label><label>时长 / 秒<input id="mDuration" type="number" min="1" max="600" step=".1" value="${seg().duration}"></label><label class="checkrow"><input id="mContinuity" type="checkbox" ${seg().continuity?'checked':''}>文字拆镜承接上一段</label><label class="checkrow"><input id="mGuideFromPrev" type="checkbox" ${(seg().guideFromPrev??seg().continuity)?'checked':''}>视频生成继承上一段（导演台段间引导）</label><p class="muted">视频引导开关随导演包导出。全局参数在顶部“段间引导”设置，第一段没有上一段可继承。</p><label>剧情摘要（应与时间线保持同一结局）<textarea id="mSummary" rows="3">${esc(workspaceText(seg().planning?.summary||''))}</textarea></label><label>本片段可用参考素材（在素材卡片中修改公共 / 本组用途）</label><div class="refgrid">${availableAssets().map(a=>`<label>${imgTag(a.path)}${esc(P.assets.find(x=>x.path===a.path)?assetLabel(P.assets.find(x=>x.path===a.path)):a.name)}</label>`).join('')}</div><p class="notice">时长修改后会按比例调整镜头时间。生成参数保留在 H3 包中，最终在导演台调整。</p>`,[{label:'保存',class:'primary',action:async()=>{const duration=Number($('mDuration').value);if(!Number.isFinite(duration)||duration<1||duration>600)throw Error('请输入 1–600 秒');const s=seg(),ratio=duration/s.duration;s.title=$('mTitle').value;s.duration=duration;s.continuity=$('mContinuity').checked;s.guideFromPrev=$('mGuideFromPrev').checked;if(s.planning||$('mSummary').value.trim())s.planning={...s.planning,summary:storedWorkspaceText($('mSummary').value)};s.shots.forEach(sh=>{sh.start=Number((sh.start*ratio).toFixed(3));sh.end=Number((sh.end*ratio).toFixed(3))});await edited();close()}}])};
async function addAssetFiles(files,scopeOverride){
 ensure();activateAssetManagement();const project=P,ownerId=seg().id,scope=scopeOverride||'public';let count=0;const problems=[];
 for(const f of Array.from(files)){
  if(P!==project){problems.push('项目已切换，剩余图片未导入');break}
  if(!['image/png','image/jpeg','image/webp'].includes(f.type)){problems.push(f.name+'：仅支持 PNG / JPG / WebP');continue}
  try{const path=await readImage(f,project);project.assets.push({id:newId(),pictureNumber:nextAssetNumber(),name:f.name.replace(/\.[^.]+$/,''),kind:'人物',path,locked:false,scope,segmentId:ownerId});project.assetsManaged=true;count++;changed()}catch(e){problems.push(f.name+'：'+e.message)}
 }
 if(count&&P===project)render();toast((count?'已导入 '+count+' 张素材。':'')+problems.join('；'))
}
$('addAsset').onclick=()=>{ensure();$('assetFile').dataset.scope='public';$('assetFile').click()};$('assetDrop').onclick=()=>{$('assetFile').dataset.scope='public';$('assetFile').click()};$('assetDrop').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();$('addAsset').onclick()}};
$('assetFile').onchange=()=>safe(async()=>{await addAssetFiles($('assetFile').files,$('assetFile').dataset.scope||'public');$('assetFile').value=''});
$('assetDrop').ondragover=e=>{e.preventDefault();$('assetDrop').classList.add('dragging')};
$('assetDrop').ondragleave=()=>$('assetDrop').classList.remove('dragging');
$('assetDrop').ondrop=e=>safe(async()=>{e.preventDefault();$('assetDrop').classList.remove('dragging');if(e.dataTransfer.files.length)await addAssetFiles(e.dataTransfer.files,'public')});
let assetDragId='';
$('assets').ondragstart=e=>{const h=e.target.closest('[data-drag-asset]');if(!h)return;assetDragId=h.dataset.dragAsset;e.dataTransfer.setData('application/x-frame-asset',assetDragId);e.dataTransfer.effectAllowed='move'};
$('assets').ondragend=()=>{assetDragId='';document.querySelectorAll('.assetCard.dropTarget').forEach(e=>e.classList.remove('dropTarget'))};
$('assets').ondragover=e=>{e.preventDefault();const card=e.target.closest('[data-asset]');if(card&&(assetDragId||Array.from(e.dataTransfer.types||[]).includes('Files'))){card.classList.add('dropTarget');e.dataTransfer.dropEffect=assetDragId?'move':'copy'}};
$('assets').ondragleave=e=>e.target.closest('[data-asset]')?.classList.remove('dropTarget');
$('assets').ondrop=e=>safe(async()=>{e.preventDefault();e.stopPropagation();const card=e.target.closest('[data-asset]'),target=card?.dataset.asset;card?.classList.remove('dropTarget');if(e.dataTransfer.files.length){if(target){if(e.dataTransfer.files.length!==1)throw Error('替换一张素材时请只拖入一张图片');await replaceAssetImage(target,e.dataTransfer.files[0])}else await addAssetFiles(e.dataTransfer.files,e.currentTarget?.id==='groupAssets'?'segment':'public');return}const from=assetDragId||e.dataTransfer.getData('application/x-frame-asset');assetDragId='';if(target&&from)await moveAsset(from,target)});
$('toggleAssets').onclick=()=>{ensure();P.assetsCollapsed=!P.assetsCollapsed;changed();renderAssets()};
$('assets').onchange=e=>safe(async()=>{const a=P.assets.find(a=>a.id===e.target.closest('[data-asset]')?.dataset.asset);if(!a)return;const key=e.target.dataset.assetField;if(!['name','kind','description','collapsed','scope'].includes(key))return;activateAssetManagement();if(key==='scope'){a.scope=e.target.value==='public'?'public':'segment';a.segmentId=e.target.value==='public'?'':e.target.value}else a[key]=key==='description'?storedWorkspaceText(e.target.value):e.target.value;P.assetsManaged=true;changed();await refreshAssetPrompts();if(key==='scope')render()});
$('assets').onclick=e=>safe(async()=>{const id=e.target.closest('[data-asset]')?.dataset.asset,a=P.assets.find(a=>a.id===id);if(!a)return;const cmd=e.target.closest('[data-asset-action]')?.dataset.assetAction;if(!cmd)return;if(cmd==='confirmManual'){await confirmManual(id);return}if(cmd==='analyzeDescription'){await analyzeAssets(id,true);return}if(cmd==='sceneLayout'){editSceneLayout(id);return}if(cmd==='dossier'){await openAssetDossier(id);return}if(cmd==='view')openImageViewer(a.path);if(cmd==='fold'){a.collapsed=!a.collapsed;changed();renderAssets()}if(cmd==='up'||cmd==='down'){const list=P.assets.filter(x=>(!x.deleted||P.showDeletedAssets)&&(a.scope==='segment'?x.scope==='segment'&&x.segmentId===a.segmentId:x.scope!=='segment')),i=list.indexOf(a),j=i+(cmd==='up'?-1:1);if(j>=0&&j<list.length)await moveAsset(id,list[j].id)}if(cmd==='replace'){$('replaceAssetFile').dataset.asset=id;$('replaceAssetFile').click()}if(cmd==='delete'){if(!confirm('删除 '+assetLabel(a)+' 的素材卡片？引用文字保留，可恢复或替换这张素材。'))return;activateAssetManagement();a.deleted=true;changed();render();toast('已删除该素材；引用编号和其他文字保持不变')}if(cmd==='restore'){a.deleted=false;changed();render();toast('已恢复原素材与引用')}if(cmd==='lock'){a.locked=!a.locked;changed();renderAssets()}});
async function replaceAssetImage(id,f){const a=P.assets.find(a=>a.id===id);if(!a||!f)return;if(!['image/png','image/jpeg','image/webp'].includes(f.type))throw Error('仅支持 PNG / JPG / WebP');activateAssetManagement();const old=a.path,newPath=await readImage(f);a.path=newPath;a.deleted=false;for(const s of P.segments)for(const r of s.refs||[])if(r.imageFile===old){r.imageFile=a.path;r.fileName=a.path.split('/').at(-1);r.subfolder='storyboard_media';r.imageB64=''}P.assetsManaged=true;changed();render();toast('已替换 '+assetLabel(a)+'，保留原编号和引用')}
$('replaceAssetFile').onchange=()=>safe(async()=>{const input=$('replaceAssetFile');try{await replaceAssetImage(input.dataset.asset,input.files[0])}finally{input.value=''}});
function displayedAssetNumber(a){const i=availableAssets().indexOf(a);return i<0?'缺失':i+1}
function workspaceText(text,followCopies=false){
 const active=availableAssets();return String(text||'').replace(/(<)?(@?Picture\s+)(\d+)(>)?/gi,(full,open,prefix,n,close)=>{
  const original=assetByNumber(Number(n));let i=active.indexOf(original);
  if(i<0&&followCopies&&original){const origin=original.originAssetId||original.id;i=active.findIndex(a=>(a.originAssetId||a.id)===origin)}
  return i<0?'[缺失引用：'+n+']':(open||'')+prefix+(i+1)+(close||'');
 });
}
function storedWorkspaceText(text){
 const active=availableAssets();return String(text||'').replace(/\[缺失引用：(\d+)\]|(@?Picture\s+)(\d+)\b/gi,(full,missing,prefix,n)=>missing?'@Picture '+missing:active[Number(n)-1]?prefix+assetNumber(active[Number(n)-1]):full);
}
function assetLabel(a){return 'Picture '+displayedAssetNumber(a)+' · '+a.name}
function mentionedAssets(text){const numbers=[...String(text||'').matchAll(/(?:@|<)Picture\s+(\d+)\b/gi)].map(m=>Number(m[1])-1);return availableAssets().filter(a=>numbers.includes(assetNumber(a)-1))}
function renderAssets(){ensureAssetNumbers();const visible=(P?.assets||[]).filter(a=>!a.deleted||P.showDeletedAssets),publicAssets=visible.filter(a=>a.scope!=='segment'),localAssets=visible.filter(a=>a.scope==='segment'&&a.segmentId===seg()?.id);$('showDeletedAssets').textContent=(P?.showDeletedAssets?'隐藏缺失素材':'显示缺失素材');$('toggleAssets').textContent=(P?.assetsCollapsed?'展开':'折叠')+' ('+publicAssets.length+')';$('assets').hidden=!!P?.assetsCollapsed;$('groupAssetsTitle').textContent=(seg()?.title||'当前片段')+' · 本组素材 ('+localAssets.length+')';const cards=assets=>assets.map((a,i)=>`<article class="assetCard" data-asset="${esc(a.id)}" ${a.deleted?'data-deleted="true"':''}><div class="assetTop"><div class="assetPicture" title="拖入一张图片替换，保留编号和引用">${imgTag(a.path)||'<span class="missingPicture">图片缺失<br>拖图替换</span>'}<b>Picture ${displayedAssetNumber(a)}${a.deleted?' · 已删除':!image(a.path)?' · 缺失':''}</b></div><div class="assetFields"><input data-asset-field="name" aria-label="素材名称" value="${esc(a.name)}"><select data-asset-field="kind" aria-label="参考类型">${['人物','场景','道具','风格'].map(k=>`<option ${a.kind===k?'selected':''}>${k}</option>`).join('')}</select></div><button data-asset-action="fold" title="折叠 / 展开素材">${a.collapsed?'▸':'▾'}</button></div><div ${a.collapsed?'hidden':''}><label class="assetScopeLabel">素材用途<select data-asset-field="scope"><option value="public" ${a.scope!=='segment'?'selected':''}>公共参考 · 所有片段</option>${P.segments.map(s=>`<option value="${s.id}" ${a.scope==='segment'&&a.segmentId===s.id?'selected':''}>本组参考 · ${esc(s.title)}</option>`).join('')}</select></label><small class="scopeBadge">${a.scope==='segment'?(a.segmentId===seg()?.id?'当前本组':'其他片段'): '公共'}${availableAssets().includes(a)?' · 本片段 Picture '+displayedAssetNumber(a):''}</small><textarea data-asset-field="description" rows="2" placeholder="具体说明：外貌、衣服、场景、需要保持的细节…">${esc(workspaceText(a.description||''))}</textarea>${typeof assetVisionBadge==='function'?assetVisionBadge(a):''}<small class="assetDropHint">拖图片到此卡片即可替换</small><div class="assetActions"><button draggable="true" data-drag-asset="${esc(a.id)}" title="按住拖动排序">⠿ 拖动</button><button data-asset-action="up" ${i===0?'disabled':''}>↑</button><button data-asset-action="down" ${i===assets.length-1?'disabled':''}>↓</button><button data-asset-action="view">查看</button><button data-asset-action="replace">替换</button><button data-asset-action="lock">${a.locked?'🔒 锁定':'锁定'}</button>${a.deleted?'<button data-asset-action="restore">恢复素材</button>':'<button data-asset-action="delete" class="danger">删除</button>'}</div></div></article>`).join('');$('assets').innerHTML=cards(publicAssets)||'<p class="muted">公共人物、场景或道具放在这里，切换片段后仍可使用。</p>';$('groupAssets').innerHTML=cards(localAssets)||'<p class="muted">本组暂无专属素材。可从上一段复制，或使用左边的公共素材。</p>';}

async function refreshAssetPrompts(){for(const s of P.segments)if(s.shots.length)s.prompt=(await api('rebuild',{...s,defaultDialogueLanguage:P.dialogueLanguage||'',assetReferences:availableAssets(s).map(a=>({index:assetNumber(a),name:a.name,kind:a.kind,description:a.description||''}))})).prompt;changed()}
async function moveAsset(from,to){activateAssetManagement();ensureAssetNumbers();const i=P.assets.findIndex(a=>a.id===from),j=P.assets.findIndex(a=>a.id===to);if(i<0||j<0||i===j)return;P.assets.splice(j,0,P.assets.splice(i,1)[0]);P.assetsManaged=true;changed();render()}


function promptModal(title,text,onSave){modal(title,`<textarea id="promptText" class="promptArea">${esc(text)}</textarea>`,[{label:'复制',action:async()=>{await navigator.clipboard.writeText($('promptText').value);toast('已复制')}},...(onSave?[{label:'保存修改',class:'primary',action:async()=>{await onSave($('promptText').value);close()}}]:[])])}
$('viewPrompt').onclick=()=>safe(async()=>{if(!seg())return;await flush();const result=await api('compiled-prompt',{projectId:P.projectId,segmentId:seg().id});promptModal('H3 Final Prompt · 当前片段（公共 + 本组编号）',result.prompt,async t=>{if(!confirm('直接修改 Prompt 后会重新解析镜头卡片，已有卡片图片仍在包内。继续保存吗？'))return;t=storedCompiledPrompt(t);const summary=t.match(/^summary:\s*([\s\S]*?)(?=^[a-z_]+:|(?![\s\S]))/im);if(summary)seg().planning={...seg().planning,summary:summary[1].trim()};seg().prompt=t;seg().shots=parseText(t,seg().duration);shotId=seg().shots[0]?.id||'';changed();render()});if(result.warnings?.length){const notes=document.createElement('div');notes.className='notice';notes.textContent='输出检查：\n'+result.warnings.join('\n');$('modalBody').prepend(notes)}});
function storedCompiledPrompt(text){return String(text).split('\n').map(line=>/^\s*Dialogue:/i.test(line)?line:convertScopePictures(line.replace(/<Subject\s+(\d+)>/gi,'<Picture $1>'),true)).join('\n')}
function parseText(text,duration){
 const re=/\[(\d+(?:\.\d+)?)s?\s*[–—\-]\s*(\d+(?:\.\d+)?)s?\]/g,ms=[...text.matchAll(re)],labels={'Camera':'camera','Expression':'expression','Dialogue':'dialogue','Sound':'sound','Spatial start':'startState','Spatial end':'endState','Dialogue language':'dialogueLanguage','Professional':'professionalNote'};
 return ms.map((m,i)=>{const body=text.slice(m.index+m[0].length,ms[i+1]?.index||text.length).split(/\n\s*(?:editing|audio|cinematography|continuity_constraints|negative_constraints|FINAL VISUAL INTENT)\s*:/)[0],parts=[...body.matchAll(/^\s*(Camera|Expression|Dialogue|Sound|Spatial start|Spatial end|Dialogue language|Professional)\s*:\s*/gim)],fields={action:body.slice(0,parts[0]?.index??body.length).trim(),camera:'',dialogue:'',sound:'',expression:'',startState:'',endState:''};parts.forEach((part,j)=>{const key=labels[Object.keys(labels).find(k=>k.toLowerCase()===part[1].toLowerCase())];let value=body.slice(part.index+part[0].length,parts[j+1]?.index??body.length).trim();if(key==='dialogueLanguage')value=value.split('。')[0].trim();fields[key]=value});return {id:newId(),start:Number(m[1]),end:Number(m[2]),...fields,image:'',firstFrame:'',lastFrame:'',locks:{identity:true,costume:false,scene:true,prop:false}}});
}
async function askAI(instruction,mode="quick"){ensure();if(typeof recordStory==='function')recordStory(seg(),'AI 拆镜前');await flush();$('aiSplit').disabled=$('aiEdit').disabled=true;try{const r=await api('plan-shots',{projectId:P.projectId,segmentId:seg().id,mode,instruction:storedWorkspaceText(instruction)});toast('AI 拆镜已加入任务队列；结果完成后预览并应用');if(typeof pollTasks==='function')await pollTasks()}catch(e){$('aiStatus').textContent='提交失败：'+e.message;throw e}finally{if(typeof syncAIStatus==='function')syncAIStatus();else $('aiSplit').disabled=$('aiEdit').disabled=false}}
$('aiSplit').onclick=()=>safe(()=>askAI('根据故事拆成适合指定时长的镜头。'));$('aiEdit').onclick=()=>safe(async()=>{const t=$('instruction').value.trim();if(!t)throw Error('先写下调整要求');await askAI(t)});
function settingsModal(){
 const a=cfg.ai||{};modal('AI 连接设置',`<label>接口<select id="aiProvider"><option value="ollama" ${a.provider==='ollama'?'selected':''}>Ollama（本机）</option><option value="openai" ${a.provider!=='ollama'?'selected':''}>OpenAI Compatible API</option></select></label><label>服务地址<input id="aiEndpoint" value="${esc(a.endpoint||'')}" placeholder="http://127.0.0.1:11434"></label><label>拆镜 / 审查模型<input id="aiModel" list="ollamaModels" value="${esc(a.model||'')}"></label><label>素材视觉模型（需要支持图片）<input id="aiVisionModel" list="ollamaModels" value="${esc(a.visionModel||'')}" placeholder="留空则使用拆镜模型；该模型必须能看图"></label><datalist id="ollamaModels"></datalist><button id="refreshModels">读取 Ollama 模型</button><p id="modelStatus" class="muted"></p><details><summary>API Key（可选）</summary><input id="aiKey" type="password" value="${esc(a.key||'')}" autocomplete="off"></details><label>素材分析输出上限 / tokens<input id="aiAssetLimit" type="number" min="512" max="8192" value="${esc(a.assetOutputTokens||2048)}"></label><label>思考模式<select id="aiThinkingMode"><option value="fast" ${(!a.thinkingMode||a.thinkingMode==='fast')?'selected':''}>快速：支持时关闭或使用低等级</option><option value="off" ${a.thinkingMode==='off'?'selected':''}>指定关闭思考（需模型支持）</option><option value="low" ${a.thinkingMode==='low'?'selected':''}>指定低等级（需模型支持）</option><option value="default" ${a.thinkingMode==='default'?'selected':''}>沿用模型默认</option></select></label><label>文字生成输出上限 / tokens<input id="aiMaxOutput" type="number" min="512" max="8192" step="256" value="${esc(a.maxOutputTokens||4096)}"></label><label class="checkrow"><input id="autoUnload" type="checkbox" ${a.autoUnload!==false?'checked':''}>切换模型或整项任务结束后自动卸载 Ollama 模型</label><p class="notice">修改字段后自动保存。先人工确认或 AI 分析并确认素材说明；之后文字拆镜不会调用视觉模型。快速思考按模型实际支持的控制设置，未检测到时沿用模型默认。Ollama 填根地址，兼容接口填到 /v1。</p><p id="settingsFeedback" class="muted" role="status"></p>`,[{label:'测试并保存',action:async()=>{try{await persist();$('settingsFeedback').textContent='正在测试连接…';const r=await api('test',cfg.ai);$('settingsFeedback').textContent=r.message;$('connection').textContent='AI 已验证连接'}catch(e){$('settingsFeedback').textContent='连接失败：'+e.message}}},{label:'保存并关闭',class:'primary',action:async()=>{await persist();close()}}]);
 const collect=()=>({provider:$('aiProvider').value,endpoint:$('aiEndpoint').value.trim(),model:$('aiModel').value.trim(),visionModel:$('aiVisionModel').value.trim(),key:$('aiKey').value,autoUnload:$('autoUnload').checked,assetOutputTokens:Math.max(512,Math.min(8192,Number($('aiAssetLimit').value)||2048)),thinkingMode:$('aiThinkingMode').value||'fast',maxOutputTokens:Math.max(512,Math.min(8192,Number($('aiMaxOutput').value)||4096))});
 let saveChain=Promise.resolve();function persist(){const ai=collect();saveChain=saveChain.catch(()=>{}).then(async()=>{await api('settings-patch',{ai});cfg.ai=ai;if($('settingsFeedback'))$('settingsFeedback').textContent='连接设置已保存，下次启动自动读取';$('connection').textContent='AI 设置已保存 · '+ai.model});return saveChain}
 for(const id of ['aiEndpoint','aiModel','aiVisionModel','aiKey','autoUnload','aiMaxOutput','aiAssetLimit','aiThinkingMode'])$(id).onchange=()=>safe(persist);
 let requestId=0;async function models(){if($('aiProvider').value!=='ollama'){$('modelStatus').textContent='兼容接口请手动填写模型';return}const id=++requestId,ai=collect();$('modelStatus').textContent='正在读取模型…';try{const r=await api('models',ai);if(id!==requestId||$('modalTitle').textContent!=='AI 连接设置'||$('aiEndpoint').value.trim()!==ai.endpoint)return;$('ollamaModels').innerHTML=r.models.map(m=>`<option value="${esc(m.name)}">`).join('');$('modelStatus').textContent='检测到 '+r.models.length+' 个模型；请选择所需模型'}catch(e){if(id===requestId&&$('modelStatus'))$('modelStatus').textContent='读取失败：'+e.message}}
 $('refreshModels').onclick=models;$('aiProvider').onchange=()=>safe(async()=>{requestId++;$('aiEndpoint').value=$('aiProvider').value==='ollama'?'http://127.0.0.1:11434':'https://api.openai.com/v1';await persist();models()});models();
}
$('settings').onclick=settingsModal;
$('unloadAI').onclick=()=> $('unloadAllAI').click();
$('uploadShot').onclick=()=>{if(!shot())return;const input=$('shotFile');input.dataset.projectId=P.projectId;input.dataset.shotId=shot().id;input.value='';input.click()};
$('shotFile').onchange=()=>safe(async()=>{
 const input=$('shotFile'),file=input.files[0];if(!file)return;
 try{
  if(P?.projectId!==input.dataset.projectId)throw Error('项目已切换，请重新选择镜头上传');
  if(!['image/png','image/jpeg','image/webp'].includes(file.type))throw Error('仅支持 PNG / JPG / WebP');
  const project=P,target=project.segments.flatMap(s=>s.shots).find(h=>h.id===input.dataset.shotId);
  if(!target)throw Error('原镜头已删除');
  const path=await readImage(file,project);
  if(!project.segments.some(s=>s.shots.includes(target))){delete project.media[path];throw Error('原镜头已删除')}
  target.image=path;changed();render();toast('分镜图片已上传，保留镜头描述和素材绑定');
 }finally{input.value=''}
});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
$('newProject').disabled=true;
safe(async()=>{token=(await (await fetch('/api/bootstrap')).json()).token;[P,cfg]=await Promise.all([api('project'),api('settings')]);shotId=seg()?.shots[0]?.id||'';render();ready=true;if(typeof syncStudioPanel==='function')syncStudioPanel();$('newProject').disabled=false;if(typeof syncReversePanel==='function')syncReversePanel()});
let viewerScale=1,viewerFit=true;
function renderViewer(){const img=$('viewerImage');img.style.width=viewerFit?'100%':Math.round(img.naturalWidth*viewerScale)+'px';img.style.maxWidth=viewerFit?'100%':'none';img.style.maxHeight=viewerFit?'calc(90vh - 90px)':'none';$('viewerDimensions').textContent=img.naturalWidth?`${img.naturalWidth} × ${img.naturalHeight} px · ${viewerFit?'适应窗口':Math.round(viewerScale*100)+'%'}`:''}
function openImageViewerSource(src,title){if(!src)return;viewerScale=1;viewerFit=true;$('viewerTitle').textContent=title;$('viewerDimensions').textContent='正在读取图片…';$('viewerImage').onload=renderViewer;$('viewerImage').onerror=()=>{$('viewerDimensions').textContent='图片读取失败，请检查参考媒体文件或重新替换'};$('viewerImage').src=src;if(!$('imageViewer').open)$('imageViewer').showModal();renderViewer()}
function openImageViewer(path){openImageViewerSource(image(path),P.assets.find(a=>a.path===path)?.name||path.split('/').at(-1))}
$('viewerClose').onclick=()=>$('imageViewer').close();$('zoomFit').onclick=()=>{viewerFit=true;renderViewer()};$('zoomActual').onclick=()=>{viewerFit=false;viewerScale=1;renderViewer()};
function zoomViewer(factor){viewerFit=false;viewerScale=Math.min(8,Math.max(.1,viewerScale*factor));renderViewer()}
$('zoomIn').onclick=()=>zoomViewer(1.25);$('zoomOut').onclick=()=>zoomViewer(.8);
document.addEventListener('click',e=>{const img=e.target.closest('img[data-preview]');if(img){e.preventDefault();e.stopImmediatePropagation();openImageViewer(img.dataset.preview)}},true);
document.addEventListener('keydown',e=>{if(['Enter',' '].includes(e.key)&&e.target.matches('img[data-preview]')){e.preventDefault();e.stopImmediatePropagation();openImageViewer(e.target.dataset.preview)}},true);

function resolveGenerationMentions(text,paths){return String(text).replace(/(?:@Picture\s+(\d+)\b|<Picture\s+(\d+)>)/gi,(full,n,tag)=>{const a=assetByNumber(Number(n||tag)),i=a?paths.indexOf(a.path):-1;return i<0?full:'参考图 '+(i+1)+'（'+a.name+(a.description?'：'+a.description:'')+'）'})}
// One menu is shared by the script, shot fields and modal prompt inputs.
let mentionInput=null,mentionStart=0,mentionEnd=0,mentionItems=[],mentionIndex=0;
const mentionFields=new Set(['script','action','camera','expression','dialogue','sound','instruction','promptText']);
function hideMentions(){$('assetMentions').hidden=true;mentionInput=null}
function showMentions(input){if(!mentionFields.has(input.id))return;const pos=input.selectionStart??input.value.length,match=input.value.slice(0,pos).match(/@([^@\n]*)$/);if(!match||match[1].length>80){hideMentions();return}mentionInput=input;mentionStart=pos-match[0].length;mentionEnd=pos;const q=match[1].toLowerCase();mentionItems=availableAssets().filter(a=>(assetLabel(a)+' '+a.kind+' '+(a.description||'')).toLowerCase().includes(q));mentionIndex=0;renderMentions();const r=input.getBoundingClientRect();$('assetMentions').style.left=Math.max(8,Math.min(r.left,window.innerWidth-330))+'px';$('assetMentions').style.top=Math.min(r.bottom+4,window.innerHeight-260)+'px';if(input.closest('dialog'))input.closest('dialog').append($('assetMentions'));else document.body.append($('assetMentions'));$('assetMentions').hidden=false}
function renderMentions(){$('assetMentions').innerHTML=mentionItems.length?mentionItems.map((a,i)=>`<button type="button" data-mention="${i}" class="${i===mentionIndex?'active':''}">${imgTag(a.path)}<span>${esc(assetLabel(a))}<small>${esc(a.kind+' · '+(a.description||'未填写说明'))}</small></span></button>`).join(''):'<p>没有匹配的素材，请先上传素材。</p>'}
function insertMention(i){const input=mentionInput,a=mentionItems[i];if(!input||!a)return;const text='@Picture '+displayedAssetNumber(a)+' ';input.setRangeText(text,mentionStart,mentionEnd,'end');hideMentions();input.focus();input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}));hideMentions();activateAssetManagement();changed()}
$('assetMentions').onmousedown=e=>{const b=e.target.closest('[data-mention]');if(b){e.preventDefault();insertMention(Number(b.dataset.mention))}};
document.addEventListener('input',e=>showMentions(e.target));
document.addEventListener('keydown',e=>{if($('assetMentions').hidden||e.target!==mentionInput)return;if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();hideMentions()}if(['ArrowDown','ArrowUp'].includes(e.key)&&mentionItems.length){e.preventDefault();mentionIndex=(mentionIndex+(e.key==='ArrowDown'?1:-1)+mentionItems.length)%mentionItems.length;renderMentions()}if(e.key==='Enter'&&mentionItems.length){e.preventDefault();e.stopImmediatePropagation();insertMention(mentionIndex)}},true);
document.addEventListener('pointerdown',e=>{if(e.target!==mentionInput&&!e.target.closest('#assetMentions'))hideMentions()});

function activateAssetManagement(){ensureAssetNumbers();if(P.assetsManaged)return;for(const s of P.segments){const mappings=new Map((s.refs||[]).map(r=>[r.index+1,assetNumber(P.assets.find(a=>a.path===r.imageFile))]).filter(([,i])=>i>0));const rewrite=t=>String(t||'').replace(/(@?Picture\s+)(\d+)\b/gi,(full,prefix,n)=>mappings.has(Number(n))?prefix+mappings.get(Number(n)):full);s.prompt=rewrite(s.prompt);for(const sh of s.shots)for(const k of ['action','camera','expression','dialogue','sound'])sh[k]=rewrite(sh[k]);for(const r of s.refs||[]){const i=P.assets.findIndex(a=>a.path===r.imageFile);if(i>=0)r.index=i}}P.assetsManaged=true}

function availableAssets(s=seg()){return (P?.assets||[]).filter(a=>!a.deleted&&a.scope!=='segment').concat((P?.assets||[]).filter(a=>!a.deleted&&a.scope==='segment'&&a.segmentId===s?.id))}
function convertScopePictures(text,reverse=false){const active=availableAssets(),indices=new Map(active.map((a,i)=>reverse?[i+1,assetNumber(a)]:[assetNumber(a),i+1]));return String(text).replace(/(@?Picture\s+)(\d+)\b/gi,(full,prefix,n)=>indices.has(Number(n))?prefix+indices.get(Number(n)):full)}

function ensureAssetNumbers(){if(!P)return;let highest=Math.max(0,...(P.assets||[]).map(a=>Number(a.pictureNumber)||0));const used=new Set();for(const [i,a] of (P.assets||[]).entries()){let n=Number(a.pictureNumber);if(!Number.isInteger(n)||n<1||used.has(n)){n=!used.has(i+1)&&!P.assets.some(x=>x!==a&&x.pictureNumber===i+1)?i+1:++highest;a.pictureNumber=n}used.add(n);highest=Math.max(highest,n)}P.nextPictureNumber=Math.max(Number(P.nextPictureNumber)||1,highest+1)}
function nextAssetNumber(){ensureAssetNumbers();return P.nextPictureNumber++}
function assetNumber(a){return a?.pictureNumber||(P?.assets||[]).indexOf(a)+1}
function assetByNumber(n){return (P?.assets||[]).find(a=>assetNumber(a)===n)}
$('showDeletedAssets').onclick=()=>{ensure();P.showDeletedAssets=!P.showDeletedAssets;changed();renderAssets()};
function repairLegacyReferences(){ensureAssetNumbers();let count=0,ambiguous=new Set();const rewrite=text=>String(text||'').replace(/\[已删除素材：([^\]]+)\]/g,(full,name)=>{const matches=P.assets.filter(a=>!a.deleted&&a.name===name.trim());if(matches.length===1){count++;return '@Picture '+assetNumber(matches[0])}ambiguous.add(name);return full});P.script=rewrite(P.script);for(const s of P.segments){s.prompt=rewrite(s.prompt);for(const sh of s.shots)for(const key of ['action','camera','expression','dialogue','sound'])sh[key]=rewrite(sh[key])}for(const a of P.assets)a.description=rewrite(a.description);if(count){changed();render()}toast('已修复 '+count+' 处旧引用'+(ambiguous.size?'；未匹配或重名的素材保留原文：'+[...ambiguous].join('、'):''));return count}
$('repairReferences').onclick=repairLegacyReferences;

$('repairPackImages').onclick=()=>safe(async()=>{ensure();await flush();const source=P.projectId,r=await api('repair-pack-images',{projectId:source});if(P.projectId!==source)return;P=r.project;render();toast('已找回 '+r.recovered+' 张图片'+(P.importWarnings?.length?'；仍缺少 '+P.importWarnings.length+' 张，请拖图替换':'，现有提示词与引用保持不变'))});

// The same card actions work in both the shared and current-segment panels.
for(const event of ['onclick','onchange','ondragstart','ondragend','ondragover','ondragleave','ondrop'])$('groupAssets')[event]=$('assets')[event];
function openGroupAssetFile(){$('assetFile').dataset.scope='segment';$('assetFile').click()}
$('addGroupAsset').onclick=openGroupAssetFile;$('groupAssetDrop').onclick=openGroupAssetFile;
$('groupAssetDrop').onkeydown=e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();openGroupAssetFile()}};
$('groupAssetDrop').ondragover=e=>{e.preventDefault();$('groupAssetDrop').classList.add('dragging')};
$('groupAssetDrop').ondragleave=()=>$('groupAssetDrop').classList.remove('dragging');
$('groupAssetDrop').ondrop=e=>safe(async()=>{e.preventDefault();$('groupAssetDrop').classList.remove('dragging');if(e.dataTransfer.files.length)await addAssetFiles(e.dataTransfer.files,'segment')});

function copyLocalAssets(source,target){
 const map=new Map();for(const a of P.assets.filter(a=>!a.deleted&&a.scope==='segment'&&a.segmentId===source.id)){
  const origin=a.originAssetId||a.id;let copy=P.assets.find(x=>!x.deleted&&x.scope==='segment'&&x.segmentId===target.id&&(x.originAssetId||x.id)===origin);
  if(!copy){copy={...structuredClone(a),id:newId(),pictureNumber:nextAssetNumber(),originAssetId:origin,segmentId:target.id};P.assets.push(copy)}map.set(assetNumber(a),assetNumber(copy));
 }
 const rewrite=t=>String(t||'').replace(/(@?Picture\s+)(\d+)\b/gi,(full,prefix,n)=>map.has(Number(n))?prefix+map.get(Number(n)):full);
 for(const a of P.assets.filter(a=>a.scope==='segment'&&a.segmentId===target.id))a.description=rewrite(a.description);target.prompt=rewrite(target.prompt);for(const sh of target.shots)for(const key of ['action','camera','expression','dialogue','sound'])sh[key]=rewrite(sh[key]);return map.size;
}
function duplicateCurrentSegment(){ensure();activateAssetManagement();ensureAssetNumbers();const source=seg(),copy=structuredClone(source);copy.id=newId();copy.videos=[];copy.title=source.title+' · 副本';copy.sourceGroupPath=source.sourceGroupPath||source.groupPath||'';copy.groupPath='asset_groups/copy_'+copy.id+'/group.json';copy.originalPrompt='';copy.continuity=true;for(const sh of copy.shots)sh.id=newId();P.segments.splice(segIndex+1,0,copy);copyLocalAssets(source,copy);segIndex++;shotId=copy.shots[0]?.id||'';changed();render();toast('已复制整段和本组素材；公共素材继续共用，副本可单独修改。视频记录仍留在原片段');return copy}
$('duplicateSegment').onclick=()=>safe(async()=>{await flush();duplicateCurrentSegment();await flush()});
$('copyGroupAssets').onclick=()=>{ensure();const candidates=P.segments.filter(s=>s.id!==seg().id);if(!candidates.length){toast('先创建第二个片段，再从其他片段复制素材');return}modal('复制素材到当前片段',`<label>来源片段<select id="copyAssetsSource">${candidates.map(s=>`<option value="${esc(s.id)}">${esc(s.title)}</option>`).join('')}</select></label><p class="muted">复制来源片段的专属素材及说明；公共素材已自动共用。复制后在本组替换图片，不会修改来源片段。</p>`,[{label:'取消',action:close},{label:'复制素材',class:'primary',action:async()=>{activateAssetManagement();ensureAssetNumbers();const source=P.segments.find(s=>s.id===$('copyAssetsSource').value);if(!source)throw Error('来源片段不存在');const count=copyLocalAssets(source,seg());changed();close();render();await flush();toast('已沿用 '+count+' 张本组素材')}}])};
$('promoteGroupAssets').onclick=()=>{ensure();activateAssetManagement();const locals=P.assets.filter(a=>!a.deleted&&a.scope==='segment'&&a.segmentId===seg().id);if(!locals.length){toast('当前没有本组专属素材');return}for(const a of locals){a.scope='public';a.segmentId=''}changed();render();toast('已将 '+locals.length+' 张素材放到左边公共区，所有片段均可使用')};

async function uprightImageData(data,mime='image/png'){const im=new Image();await new Promise((resolve,reject)=>{im.onload=resolve;im.onerror=()=>reject(Error('无法读取图片方向'));im.src=data});if(im.naturalWidth*im.naturalHeight>64000000)throw Error('图片过大，请先缩小');const canvas=document.createElement('canvas');canvas.width=im.naturalWidth;canvas.height=im.naturalHeight;canvas.getContext('2d').drawImage(im,0,0);return canvas.toDataURL(mime,.97)}
async function normalizeAssetOrientation(id){const project=P,a=P.assets.find(v=>v.id===id);if(!a)return;const data=await uprightImageData('data:'+(a.path.endsWith('.jpg')||a.path.endsWith('.jpeg')?'image/jpeg':a.path.endsWith('.webp')?'image/webp':'image/png')+';base64,'+P.media[a.path]);if(P!==project||!P.assets.includes(a))throw Error('素材已变化');const old=a.path;a.path='storyboard_media/'+newId()+'.png';P.media[a.path]=data.split(',')[1];for(const s of P.segments)for(const r of s.refs||[])if(r.imageFile===old){r.imageFile=a.path;r.fileName=a.path.split('/').at(-1);r.subfolder='storyboard_media';r.imageB64=''}changed();await flush();render();toast('图片已按浏览器显示方向固化，请重新核对说明和布局。')}
